modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="realistic_guns"
version="1.0.0"
displayName="RealisticGuns"
description="A modular gun mod with GunPack support."

[[dependencies.realistic_guns]]
modId="neoforge"
type="required"
versionRange="[21.1.228,)"
ordering="NONE"
side="BOTH"

[[dependencies.realistic_guns]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.realistic_guns]]
modId="geckolib"
type="required"
versionRange="[4.7,)"
ordering="NONE"
side="BOTH"